services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: webfpv
      POSTGRES_PASSWORD: webfpv
      POSTGRES_DB: webfpvleaderboard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
